spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: sonwrkmaro@gmail.com
    password: faphxjtuuoyumwup
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL:

app:
  jwt-secret: 9dc5c51e926d990d6ca268a03153114fa73d4f313135fd2e7336157f8915e72e
  jwt-expiration-milliseconds: 604800
